name: "[reusable] notify slack about new PR"

on:
  workflow_call:
    secrets:
      WEBHOOK_URL:
        required: true

jobs:
  notifySlack:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack on PR
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          if [ -z "${SLACK_WEBHOOK_URL}" ]; then
            echo "SLACK_WEBHOOK_URL is not set"
            exit 1
          else
            echo "SLACK_WEBHOOK_URL is set"
          fi

          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_TITLE_ESCAPED=$(echo "$PR_TITLE" | sed 's/"//g')
          PR_URL="${{ github.event.pull_request.html_url }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          PR_CREATOR="${{ github.event.pull_request.user.login }}"
          PR_CREATOR_NAME="${{ github.event.pull_request.user.name }}"
          PR_DIFF_URL="${{ github.event.pull_request.diff_url }}"
          REPO_NAME="${{ github.repository }}"
          ORG_NAME="${{ github.event.pull_request.organization }}"
          REPO_URL="${{ github.server_url }}/${{ github.repository }}"
          curl -X POST -H 'Content-type: application/json' -d "{\"text\": \"A new pull request <${PR_URL}|\`${ORG_NAME}/${REPO_NAME}/#${PR_NUMBER}\`> has been opened by \`${PR_CREATOR}\`:\\n*${PR_TITLE_ESCAPED}* \\n<${PR_URL}|View Pull Request> \\n<${REPO_URL}|View Repository> \\n<${PR_DIFF_URL}|Show Raw Diff>\"}" $SLACK_WEBHOOK_URL
