name: "[reusable] notify slack about stale PR"

on:
  workflow_call:
    secrets:
      WEBHOOK_URL:
        required: true

jobs:
  notifySlack:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack on PR
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          if [ -z "${SLACK_WEBHOOK_URL}" ]; then
            echo "SLACK_WEBHOOK_URL is not set"
            exit 1
          else
            echo "SLACK_WEBHOOK_URL is set"
          fi

          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_TITLE_ESCAPED=$(echo "$PR_TITLE" | sed 's/"//g')
          PR_URL="${{ github.event.pull_request.html_url }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          PR_CREATOR="${{ github.event.pull_request.user.login }}"
          PR_REPOSITORY_NAME="${{ github.repository }}"

          curl -X POST -H 'Content-type: application/json' -d "{\"text\": \"Pull request <${PR_URL}|\`${PR_REPOSITORY_NAME}#${PR_NUMBER}: ${PR_TITLE_ESCAPED}\`>  from \`${PR_CREATOR}\` needs some love, it\'s stale for \`3\` days\"}" $SLACK_WEBHOOK_URL
